### ISSUE TITLE
3D editor uses 100% CPU

### ISSUE THREAD

**Issue by Zyin055** [hnmr293/posex#12]
After clicking the `Send this image to ControlNet` checkbox and the 3D editor appears, it uses 100% of the CPU if your browsers hardware acceleration is turned off. Please add some sort of FPS limiter to the 3D app if possible.

In Edge the setting is called "Use hardware acceleration when available".

**Comment by hnmr293** [comment]
I've fixed it. Thank you for information to reproduce.
But improvement is limited.
In my environment, CPU usage becomes 100% to 75%.

![image](https://user-images.githubusercontent.com/120772120/223137902-a89a71a0-3b1a-461c-9769-d1854822431e.png)
