### ISSUE TITLE
Posex panel is empty

### ISSUE THREAD

**Issue by linnkoln** [hnmr293/posex#17]
![image](https://user-images.githubusercontent.com/60001135/223099037-bce61dbd-d427-40c9-a0b2-8f08ec2dc3b2.png)

**Comment by Htgan** [comment]
Same problem.

**Comment by hnmr293** [comment]
okay.
Please click the checkbox `Send this image to ControlNet.` and wait a few seconds.
If you still get nothing, press `F12` key. 
Then copy `Console` content and paste it here.

cf. Console of Devtools is like this:
https://learn.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/media/console-intro-console-main.msft.png

**Comment by linnkoln** [comment]
Thanks, clicking the checkbox `Send this image to ControlNet` helped!
