### ISSUE TITLE
editor doesn't appear when I click send to control net

### ISSUE THREAD

**Issue by gsgoldma** [hnmr293/posex#19]
Not sure why it's happening. There's no error in the console. As of this post I'm up to date on commits.

**Comment by hnmr293** [comment]
Thanks for your feedback.
Please tell me your environment.
- OS
- browser and its version
- local, or cloud such as colab
- if local, how you had installed webui (git or any installer)

**Comment by gsgoldma** [comment]
windows 10, firefox 110.0.1 64-bit
local
git python 3.10.6
not  sure what symlink is probably not

**Comment by HomAfromPTZ** [comment]
Same problem.

- Win 10 Pro 22H2 v.19045.2673
- Chrome 110.0.5481.178 / Opera 95.0.4635.46 / Edge 110.0.1587.63
- Portable install: https://github.com/serpotapov/stable-diffusion-portable

**Comment by Sphinx2k** [comment]
> UPD: Editor appears if you open it from txt2img tab right after start of the server (or after UI/page reload), then it works on other tabs. If you try to enable it from img2img - it doesn't work at all.

I can confirm this behavior.

**Comment by hnmr293** [comment]
Thank you guys,
Any errors in Devtools' console (`F12`) or your terminal?
I could not reproduce this issue.

My procedure is:

1) In txt2img I've generated an image with posex/controlnet.
![image](https://user-images.githubusercontent.com/120772120/223410323-16e753e6-f9f1-46ca-91f8-30975cab1196.png)

2) Send that image to img2img, and create another pose with posex in img2img tab.
![image](https://user-images.githubusercontent.com/120772120/223411398-353e919d-84bf-4eb8-a9d5-7e7d89456681.png)

3. Then I've generated an image in img2img tab.
![image](https://user-images.githubusercontent.com/120772120/223412107-9930a27f-2694-4e08-ba62-7831440d929a.jpg)

It seems to be working well.

**Comment by HomAfromPTZ** [comment]
> Any errors in Devtools' console (`F12`) or your terminal?

Yes, If you launch Posex from img2img tab it throws:
```
Uncaught ReferenceError: t2i_called is not defined
    at HTMLInputElement.i2i_callback (posex-webui.js?1678147247.9715118:53:22)
i2i_callback @ posex-webui.js?1678147247.9715118:53
```
Screencast of both (working / not-working) scenarios:
https://youtu.be/CMfE9zQSuIA

**Comment by hnmr293** [comment]
Oh, sorry! I misunderstood.
I have fixed it. Please try it again.

**Comment by eshutoff** [comment]
> Oh, sorry! I misunderstood. I have fixed it. Please try it again.

Hi, have the very similar issue on:
windows 10
firefox 111.0.1 (64-bit)
and 
Brave [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)]
local
git python 3.10.6

But there are some differences - it works only on img2img tab, and after be opened there it appeared on txt2img too. Could you recommend any solution?

**Comment by lindsayfowler** [comment]
Same problem in latest install 24/May/2023. The Posex panel appears in both txt2img and img2img, but there's only a checkbox and a "Target ControlNet" list box, no other controls appear.

I don't think it's a  problem associated with one platform. I am on a Mac and I have tried Chrome and Safari. There were no exceptions reported in the developer console, but plenty of warnings about missing controls:

some put not all:
[Warning] [svelte-i18n] The message "Reload UI" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "🔄" was not found in "en-AU", "en". (index.4395ab38.js, line 32, x5)
[Warning] [svelte-i18n] The message "Request browser notifications" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Download localization template" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Reload custom script bodies (No ui updates, No restart)" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Show all pages" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Apply and restart UI" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Check for updates" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Load from:" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Run" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Install" was not found in "en-AU", "en". (index.4395ab38.js, line 32)
[Warning] [svelte-i18n] The message "Change checkpoint" was not found in "en-AU", "en". (index.4395ab38.js, line 32)

**Comment by Seal-Pavel** [comment]
Та же проблема. 
<img width="597" alt="image" src="https://github.com/hnmr293/posex/assets/89728640/96692e25-2078-4a9b-95c6-0b132e3b738f">
