### ISSUE TITLE
Posex Ui not working correctly

### ISSUE THREAD

**Issue by Gollum0002** [hnmr293/posex#23]
Posex is showing up in stable diffusion however I cannot use it since the ui seems to be bugged
![Screenshot (16)](https://user-images.githubusercontent.com/109045152/223878194-f368824b-3987-451f-8d1c-1959afdeb457.png)

I have installed control net/posex through the extension manager as can be seen below
![Screenshot (17)](https://user-images.githubusercontent.com/109045152/223878395-f8b21a0f-a88a-4191-aba3-8cc8088a084e.png)

This might be an issue on my part since I did not find many posts regarding this issue however I cannot find any reasons for why that might be since I followed the instructions and have done everything accordingly.

This is the only post going through the same issue as me : https://www.reddit.com/r/SDtechsupport/comments/11kh71g/posex_ui_not_appearing_correctly_on_sd/

**Comment by Gollum0002** [comment]
This is how the ui looks initially 
![Screenshot (69)](https://user-images.githubusercontent.com/109045152/223879408-692a0b12-28a2-4b39-b8ea-e26ba4dad018.png)

after I tick and untick the send to control net box, the ui expands but is not functional

**Comment by Gollum0002** [comment]
The issue seems to occur on browsers other than Chrome, I have tested it on Microsoft edge, opera gx and chrome, Posex was working correctly on chrome

**Comment by mockinbirdy** [comment]
Same problem. Usually chrome is the one causing troubles. **The author should really look into it.** 
Have you found the workaround yet?

**Comment by Gollum0002** [comment]
Not really, I just used chrome, will switch to opera again when its fixed though, chrome is performance hungry

**Comment by andrechoi** [comment]
> The issue seems to occur on browsers other than Chrome, I have tested it on Microsoft edge, opera gx and chrome, Posex was working correctly on chrome. ![Screenshot (71)](https://user-images.githubusercontent.com/109045152/224076544-946677ae-02a4-4fdb-b797-e1b8d214a8eb.png)
> 
> This might have something to do with the issue

True!! I was not using Chrome browser and the it bugged, after switching to chrome Posex is working fine! Thank you!!

**Comment by mockinbirdy** [comment]
Well, that is NOT a solution. I am not going to download chrome just for one extension. This issue is crucial and should be addressed.

**Comment by 2blackbar** [comment]
for me posex doesnt show up at all, not sure why cause its activated in extensions panel and i restarted dozens of times

**Comment by BmBKun** [comment]
> This is how the ui looks initially ![Screenshot (69)](https://user-images.githubusercontent.com/109045152/223879408-692a0b12-28a2-4b39-b8ea-e26ba4dad018.png)
> 
> after I tick and untick the send to control net box, the ui expands but is not functional

Same problem, the Posex interface does not appear. I use google chrome, so does my friend...

**Comment by Bipedal-Moose** [comment]
I'm also experiencing this issue in Chrome. I have both ControlNet and Posex installed on latest Automatic1111. After booting up A1111, the accordion in t2i only shows the _send this image to controlnet_

**Comment by consecutiotemporum** [comment]
Same here.

**Comment by eshutoff** [comment]
Hi, have the very similar issue on:
windows 10
firefox 111.0.1 (64-bit)
and
Brave [Version 1.49.132 Chromium: 111.0.5563.147 (Official Build) (64-bit)]
local
git python 3.10.6

I see this in the console:
[svelte-i18n] The message "Run" was not found in "en".
regarding the http://localhost:7860/ui/node_modules/.pnpm/svelte-i18n@3.3.13_svelte@3.49.0/node_modules/svelte-i18n/dist/runtime.esm.js

But there are some differences - it works only on img2img tab, and after be opened there it appeared on txt2img too. Could you recommend any solution?

**Comment by HomAfromPTZ** [comment]
After "removeChild fix" there is another bug now.
If you enable and disable posex tab and click "Generate" it throws error:
posex-webui.js?1680351184.6494553:41 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'click')
    at posex-webui.js?1680351184.6494553:41:63
    at new Promise (<anonymous>)
    at js2py (posex-webui.js?1680351184.6494553:22:16)
    at HTMLElement.<anonymous> (posex-webui.js?1680351184.6494553:311:23)

**Comment by zyip** [comment]
version 0.4 works fine, remove your installation and try this:

git clone https://github.com/hnmr293/posex
cd posex
git checkout tags/v0.4

hope hnmr293 push a new version in days.
