### ISSUE TITLE
Vertical lines when saving pose

### ISSUE THREAD

**Issue by ocdwolf** [hnmr293/posex#24]
Hello, I believe I've correctly followed the install instructions. However when saving a pose, it only saves an image with vertical lines. Same issue whether I save inside of posex or download pose to pc. All extensions are up to date.

![posex_error](https://user-images.githubusercontent.com/118213843/223880114-cd696fab-84da-4e7a-b900-d455aa0a8314.JPG)

Not sure what the problem could be, any help is appreciated. 
Thank you!

**Comment by hnmr293** [comment]
hmm... plz let me know your environment
OS:
CPU:
GPU:
Browser:

**Comment by ocdwolf** [comment]
OS: Windows 10
CPU: i9-11900k
GPU: 3080ti 12gb
Browser: LibreWolf

Figured it out, it was the browser. LibreWolf is a more privacy focused firefox clone and has a lot of settings. 
I think it was because my WebGL setting was off.

Thank you!
